export enum Memory {
  Round = 1,
  RollCount,
  BoughtCards,
  Effects,
  FreeTurn,
  KeepCardPlayed,
  Phase,
  RivalSmashCount,
  DecreaseDiceCount,
  TitanicBatteries,
  DiceFacesSolved,
  CamouflageRolledDiceCount,
  Immune,
  ActivePlayer,
  Dominate,
  SkipReboot,
  ConsumedPower,
  AdditionalRollFaces
}