  export enum RuleId {
  RollDice = 1,
  PullPawn,
  PullDestructionPawn,
  GainEnergy,
  Smash,
  Buy,
  ChangePlayer,
  Effect,
  Heal,
  Dominate,
  MoveBuzzToken,
  Hibernation,
  InShape,
  MadeInALab,
  Rebooting,
  Camouflage,
  SuperConductor,
  TitanicBatteries,
  UnstableDna,
  AfterDiceResolution,
  ResolveDice,
  EndOfTurn,
  TeslaImpulse,
    PreventDamages,
    GainWhiteDiceToken,
    ThePartyIsOver,
  // TODO: REMOVE IT (FreeTurn)
  FreeTurn,
  OperationMedia
}
