import { Buzz } from '../Buzz'
import { EnergyCard } from './EnergyCard'
import { Timing } from './Timing'

export type CardCharacteristics = {
  cost: number,
  timing: Timing
  buzz?: Buzz,
}

export const energyCardCharacteristics: Record<EnergyCard, CardCharacteristics> = {
  [EnergyCard.AcidAttack]: { cost: 6, timing: Timing.Keep, buzz: Buzz.Buzz5 },
  [EnergyCard.AdrenalineAugment]: { cost: 5, timing: Timing.Keep },
  [EnergyCard.AlienMetabolism]: { cost: 2, timing: Timing.Keep, buzz: Buzz.Buzz7 },
  [EnergyCard.AntimatterPellets]: { cost: 5, timing: Timing.Keep },
  [EnergyCard.ArmorPlating]: { cost: 6, timing: Timing.Keep, buzz: Buzz.Buzz1 },
  [EnergyCard.BreakingNews]: { cost: 6, timing: Timing.Keep, buzz: Buzz.Buzz8 },
  [EnergyCard.Camouflage]: { cost: 4, timing: Timing.Keep },
  [EnergyCard.CannonBall]: { cost: 7, timing: Timing.Discard, buzz: Buzz.Buzz7  },
  [EnergyCard.Dominate]: { cost: 3, timing: Timing.Discard, buzz: Buzz.Buzz10  },
  [EnergyCard.ElectricalAura]: { cost: 4, timing: Timing.Keep, buzz: Buzz.Buzz6   },
  [EnergyCard.Energize]: { cost: 10, timing: Timing.Discard, buzz: Buzz.Buzz6  },
  [EnergyCard.ExtraHead]: { cost: 7, timing: Timing.Keep },
  [EnergyCard.EyeOfTheStorm]: { cost: 2, timing: Timing.Keep, buzz: Buzz.Buzz8  },
  [EnergyCard.Frenzy]: { cost: 6, timing: Timing.Discard },
  [EnergyCard.GentleGiant]: { cost: 5, timing: Timing.Keep, buzz: Buzz.Buzz4  },
  [EnergyCard.GiantBrain]: { cost: 4, timing: Timing.Keep },
  [EnergyCard.Hibernation]: { cost: 5, timing: Timing.Keep },
  [EnergyCard.HorsDOeuvre]: { cost: 3, timing: Timing.Discard, buzz: Buzz.Buzz1  },
  [EnergyCard.InShape]: { cost: 4, timing: Timing.Keep },
  [EnergyCard.InTheShadows]: { cost: 5, timing: Timing.Keep, buzz: Buzz.Buzz9  },
  [EnergyCard.JetsScrambled]: { cost: 5, timing: Timing.Discard, buzz: Buzz.Buzz12 },
  [EnergyCard.Kaijutsu]: { cost: 5, timing: Timing.Discard, buzz: Buzz.Buzz10 },
  [EnergyCard.LightingSpeed]: { cost: 4, timing: Timing.Keep, buzz: Buzz.Buzz9  },
  [EnergyCard.MadeInALab]: { cost: 2, timing: Timing.Keep, buzz: Buzz.Buzz5  },
  [EnergyCard.MomentOfRespite]: { cost: 4, timing: Timing.Discard, buzz: Buzz.Buzz9  },
  [EnergyCard.MonsterCoaster]: { cost: 7, timing: Timing.Discard  },
  [EnergyCard.Monumental]: { cost: 5, timing: Timing.Discard, buzz: Buzz.Buzz2 },
  [EnergyCard.NaturalSelection]: { cost: 4, timing: Timing.Keep },
  [EnergyCard.OperationMedia]: { cost: 6, timing: Timing.Discard, buzz: Buzz.Buzz7 },
  [EnergyCard.Photoshoot]: { cost: 2, timing: Timing.Discard, buzz: Buzz.Buzz4 },
  [EnergyCard.Rebooting]: { cost: 3, timing: Timing.Keep, buzz: Buzz.Buzz1 },
  [EnergyCard.Regeneration]: { cost: 4, timing: Timing.Keep },
  [EnergyCard.SackTheStadium]: { cost: 8, timing: Timing.Discard, buzz: Buzz.Buzz11 },
  [EnergyCard.Scrappy]: { cost: 2, timing: Timing.Keep, buzz: Buzz.Buzz6 },
  [EnergyCard.SeismicTest]: { cost: 5, timing: Timing.Discard },
  [EnergyCard.SignatureMove]: { cost: 6, timing: Timing.Keep, buzz: Buzz.Buzz11 },
  [EnergyCard.SnackTime]: { cost: 3, timing: Timing.Discard },
  [EnergyCard.SpikedTail]: { cost: 4, timing: Timing.Keep },
  [EnergyCard.Superconductor]: { cost: 2, timing: Timing.Keep },
  [EnergyCard.TeslaImpulse]: { cost: 6, timing: Timing.Discard, buzz: Buzz.Buzz12 },
  [EnergyCard.ThePartyIsOver]: { cost: 4, timing: Timing.Discard, buzz: Buzz.Buzz11 },
  [EnergyCard.ThermonuclearCooking]: { cost: 7, timing: Timing.Discard, buzz: Buzz.Buzz2 },
  [EnergyCard.ThunderStomp]: { cost: 4, timing: Timing.Keep },
  [EnergyCard.TitanicBatteries]: { cost: 4, timing: Timing.Keep, buzz: Buzz.Buzz10 },
  [EnergyCard.TooCute]: { cost: 3, timing: Timing.Discard, buzz: Buzz.Buzz4 },
  [EnergyCard.TrendSetter]: { cost: 3, timing: Timing.Keep, buzz: Buzz.Buzz8 },
  [EnergyCard.Unchained]: { cost: 3, timing: Timing.Keep, buzz: Buzz.Buzz12 },
  [EnergyCard.UnstableDna]: { cost: 3, timing: Timing.Keep, buzz: Buzz.Buzz5 },
  [EnergyCard.Unstoppable]: { cost: 3, timing: Timing.Keep },
  [EnergyCard.UtterDestruction]: { cost: 4, timing: Timing.Keep, buzz: Buzz.Buzz2 },
}