export enum LocationType {
  MainBoard = 1,
  MonsterBoard,
  PowerCardDeck,
  PowerCardOnBoard,
  HealthCounter,
  FameTrack,
  DestructionTrack,
  BuzzStock,
  PlayerHand,
  EnergyStock,
  PlayerBuzzToken,
  PlayerRolledDice,
  WhiteDiceStock,
  PlayerEnergy,
  Discard,
  PlayerKeepCards,
}
