export enum LocationType {
  MainBoard = 1,
  MonsterBoard,
  PowerCardDeck,
  PowerCardOnBoard,
  HealthCounter,
  FameTrack,
  DestructionTrack,
  BuzzStock,
  PlayerDiceRoll,
  EnergyStock,
  PlayerBuzzToken,
  PlayerDiceKeep,
  WhiteDiceStock,
  PlayerEnergy,
  Discard,
  PlayerKeepCards,
  PlayerDiceToken,
  OnPowerCard,
  BuyArea,
  WhiteTokenStock,
  PowerCardCost,
  SpotlightArea,
  PowerCardBuzz
}
